version: "3"

services:
  fastapi:
    image: bletvaska/python
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    user: "${UID}:${GID}"
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

