global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:


scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ['fastapi:80']

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: grafana
    metrics_path: "/metrics"
    scheme: "http"
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets: ['grafana:3000']

